---
- name: Install Packages
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Tasks for Linux
      block:
        - name: Ensure required packages are installed
          ansible.builtin.package:
            name:
              - bat
              - build-essential
              - make
              - pipx
              - stow
              - tmux
              - zsh
            state: latest
      when: ansible_os_family == "Linux"
