---
- name: Install Packages
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Tasks for Linux
      block:
        - name: Ensure required packages are installed
          ansible.builtin.package:
            name:
              - bat
              - build-essential
              - fzf
              - keychain
              - make
              - pipx
              - stow
              - tmux
              - zsh
            state: latest
        - name: Download and install git-delta deb
          ansible.builtin.apt:
            deb: https://github.com/dandavison/delta/releases/download/0.13.0/git-delta_0.13.0_amd64.deb
      when: ansible_system == "Linux"
